CREATE TABLE borrowers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(320) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_borrower_email UNIQUE (email)
);

CREATE TABLE book_catalog (
    isbn VARCHAR(17) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL
);

CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn VARCHAR(17) NOT NULL REFERENCES book_catalog(isbn),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    borrower_id BIGINT NOT NULL REFERENCES borrowers(id),
    book_id BIGINT NOT NULL REFERENCES books(id),
    borrowed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_active_loan_book UNIQUE (book_id)
);

CREATE INDEX idx_books_isbn ON books(isbn);
CREATE INDEX idx_loans_borrower ON loans(borrower_id);
